c_sharp/Harbor Control System/Controllers/BoatController.cs
using Harbor_Control_System.Entity.Boat;
using Harbor_Control_System.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Harbor_Control_System.Controllers
{
    public class BoatController : Controller
    {
        private BoatService _boatService;

        public BoatController()
        {
            _boatService = new BoatService();

        }
        public List<Boat> GetBoatType()
        {
            var boatType = _boatService.GetBoatTypeList();

            return boatType;
        }

        public ActionResult SelectedBoat()
        {
            return View(_boatService.GetBoatTypeList());
        }
        [HttpPost]
        public ActionResult SelectedBoat(string data)
        {
            var temp = data;

            ViewBag.lesiba = "Ofenste";// BoatList = _boatService.GetBoatList();
            return View();
        }

        public List<SelectListItem> Boats()
        {
            return null;// new SelectListItem() { }
        }
    }
}

c_sharp/Harbor Control System/Controllers/HarborController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace Harbor_Control_System.Controllers
{
    public class HarborController : Controller
    {
        private enum Status { Occupied, Not_Occupied }
        private string currentStatus;
        public string CurrentStatus
        {
            get
            {
                var random = new Random();
                var value = random.Next(2);

                switch (value)
                {
                    case 0:
                        currentStatus = Status.Occupied.ToString();
                        break;
                    case 1:
                        currentStatus = Status.Not_Occupied.ToString().Replace('_', ' ');
                        break;
                }
                return currentStatus;
            }
        }

        public string Output()
        {

            if (currentStatus == Status.Occupied.ToString())
            {
                return "The Harbor entrance is currently in use, please wait few minutes";
            }
            else
            {
                return "Please proceed to the Harbor entrnce";

                //
            }
        }

        //

    }
}

c_sharp/Harbor Control System/Controllers/WeatherController.cs
using Harbor_Control_System.Entity;
using Harbor_Control_System.Exception_Handling;
using Harbor_Control_System.Services;
using Microsoft.AspNetCore.Mvc;

namespace Harbor_Control_System.Controllers
{
    public class WeatherController : Controller
    {
        public WeatherController()
        {
            try
            {
                Weather = WeatherService.GetWeather().Result;
            }
            catch (WeatherException)
            {

                throw new WeatherException("Please check you internet connection");
            }
        }

        public Weather Weather { get; }

    }
}

c_sharp/Harbor Control System/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="card">
    <h5 class="text-center">Location 4  66 Information</h5>
    @*<p>Location: @Model._weather.City.Name </p>
    <p>Logitude: @Model._weather.City.Coordinates.Longitude </p>
    <p>Latitude:  @Model._weather.City.Coordinates.Latitude </p>
    <p>Wind speed: @Model._weather.Forecast[0].WindSpeed </p>*@
</div>


<div class="card">
    <h5 class="text-center">Hobor Status</h5>
    <p>Status: @Model._currentStatus</p>
</div>



@*@Html.DropDownList("BoatName", new SelectList(Model._boardList), "Select board type", new { @class = "form-control" });
    <button type="Submit" class="btn btn-success submit">Send</button>*@

<div>
    @using (Html.BeginForm("SelectedBoat", "Boat", FormMethod.Post))
    {
        @Html.DropDownListFor(b => b.BoatType, new SelectList(Model._boatTypeList), "Select new", new { @class = "form-control dropdown" });
        <input type="submit"/>
    }
    end div
</div>
    <br />
    <p>
        viewbg is: @ViewBag.lesiba;
    </p>
    @*Please disable this form/inputs if status id occupied*@

    @{
        var status = "Not Occupiead";// Model._currentStatus;
        if (status == "Not Occupied")
        {
            <div>
                <div class="card ">
                    <h5 class="text-center">Boat Information</h5>
                    @*Select boat type using dropdown arrow*@

                    <div class="btn-group">
                        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Select board type</button>
                        <div class="dropdown-menu">
                            @{

                                foreach (var boardType in Model._boatTypeList)
                                {
                                    <a class="dropdown-item" href="">@boardType</a>
                                }

                            }
                        </div>

                    </div>


                </div>


                @*Output*@

                <div class="card">
                    <h5 class="text-center">Action</h5>
                    <p> </p>
                </div>
            </div>
        }
    }

c_sharp/Harbor Control System/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>@ViewData["Title"] - Harbor Control System</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm justify-content-center navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Harbor Control System</a>              
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Harbor Control System
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>